apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: life-ingress
  namespace: life
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - life.xinutec.org
      secretName: life-tls
  rules:
    - host: life.xinutec.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: life-app
                port:
                  number: 80
