apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coach-ingress
  namespace: coach
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - coach.xinutec.org
      secretName: coach-tls
  rules:
    - host: coach.xinutec.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coach-app
                port:
                  number: 80
