-- GENERATED by nixos-config/scripts/render_clusters.py from network.nix.
-- Do not edit; the kubes model keeps a copy (see that script).
let Edge = < Frontdoor | IngressNginx >

in  { Edge, clusters = { amun = Edge.IngressNginx, isis = Edge.Frontdoor } }
