{
 "title": "Picade Monitoring",
 "description": "Public view on Picade metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((count by (agent_hostname) (count(node_cpu_seconds_total) by (cpu, agent_hostname))) \n- \navg by (agent_hostname) (sum by (agent_hostname, mode)(irate(node_cpu_seconds_total{mode='idle'}[$__rate_interval])))) * 100) \n/ \ncount by(agent_hostname) (count(node_cpu_seconds_total) by (cpu, agent_hostname))",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(agent_hostname) (node_hwmon_temp_celsius)",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 -\n(\n  avg by (agent_hostname) (node_memory_MemAvailable_bytes) /\n  avg by (agent_hostname) (node_memory_MemTotal_bytes)\n* 100\n)",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(25,irate(node_disk_io_time_seconds_total{device=~\"mmcblk\\\\d+\"}[$__rate_interval]))",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"wlan0\"}[$__rate_interval])",
     "legendFormat": "{{agent_hostname}}: recv"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"wlan0\"}[$__rate_interval])",
     "legendFormat": "{{agent_hostname}}: send"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(25,100 - node_filesystem_avail_bytes{fstype!~\"(nfs4|tmpfs|)\", mountpoint!~\"(.*/kubelet/.*|/nix/store|/run/keys|/home|)\"}/node_filesystem_size_bytes{fstype!~\"(nfs4|tmpfs|)\", mountpoint!=\"\"}*100)",
     "legendFormat": "{{agent_hostname}}: {{mountpoint}}"
    }
   ]
  }
 ]
}